
services:
  web:
    build: .
    container_name: fulldesign_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - sqlite_data:/app/db
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env

volumes:
  sqlite_data:
  static_volume:
  media_volume:
